### ISSUE TITLE
Add a script/executable to perform sanity checking

### ISSUE THREAD

**Issue by sarthakpati** [FETS-AI/Front-End#22]
**Is your feature request related to a problem? Please describe.**
Currently, there should be diagnostic tool to check the input data that the collaborators can check the validity of the data.

**Describe the solution you'd like**
- Check for [image sanity](https://github.com/FETS-AI/LabelFusion/blob/main/LabelFusion/itkUtils.py#L29) 
- Each subject has the 4 modalities and the "final_seg" label present
- Ensure that only `[0,1,2,4]` labels are present for each subject
  - If not, then provide the message that the collaborator should rectify this.
  - Show number of voxels for the corresponding label ID
  - `subject_id,label_file,label,number_of_voxels`

**Describe alternatives you've considered**
N.A.

**Additional context**
Caught by @ujjwalbaid0408

**Comment by sarthakpati** [comment]
The final output has been changed to give the following information in case there is a problematic case or missing label:
```
subject_id,recommeded_initial_annotation
```

**Comment by sarthakpati** [comment]
Done.

**Comment by umgpy** [comment]
Hi we added additional processed and corrected data to the already existing DataForFeTS folder. Upon running _SanityCheck_ script I encountered this error.

>Traceback (most recent call last):
> File "./SanityCheck.py", line 197, in <module>
>    main()
>  File "./SanityCheck.py", line 124, in main
>    first, *rest = files_for_subject.items() # split the dict>
ValueError: not enough values to unpack (expected at least 1, got 0)Going through the python script I don't see any reason to expect this error

This is due to the following line-
 ` for dirs in os.listdir(inputDir):`
 `   if dirs != 'logs': # don't perform sanity check for the 'logs' folder`

After removing split_info folder there were of course no issues, but it would be helpful if the script handled excluding the other folder too in case anyone is planning to add new data.

Thanks
